#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

mkdir "${SCRIPT_DIR}/IR" &> /dev/null

clang-18 \
    -I "${SCRIPT_DIR}/include" \
    -S \
    -emit-llvm \
    -O2 \
    "${@}" \
    "${SCRIPT_DIR}/src/app.c" \
    -o "${SCRIPT_DIR}/IR/app.ll"